name: Build & Deploy (Production)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'
      # - 'packages/another-package/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: test
        run: yarn test

      - name: Deploy
        run: echo "Deployed"